// Code generated by Icestudio 0.11.3w202403120303202403120303202403120303202403120303202403120303202403120303202403120303202403120303202403120303202403120303202403120303202403120303202403120303

`default_nettype none

//---- Top entity
module main (
 input [9:0] vf2cc41,
 input [9:0] v1f8542,
 input v372172,
 input v2fd51b,
 input v7964d5,
 input v0089e3,
 input vf35661,
 input va95c45,
 input v494eb7,
 input v988c99,
 input v5681d5,
 input ve895ff,
 input v10d98e,
 output [29:0] v16fc4d
);
 wire [0:9] w0;
 wire [0:9] w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire [0:29] w13;
 assign w0 = vf2cc41;
 assign w1 = v1f8542;
 assign w2 = v372172;
 assign w3 = v2fd51b;
 assign w4 = v7964d5;
 assign w5 = v0089e3;
 assign w6 = vf35661;
 assign w7 = va95c45;
 assign w8 = v494eb7;
 assign w9 = v988c99;
 assign w10 = v5681d5;
 assign w11 = ve895ff;
 assign w12 = v10d98e;
 assign v16fc4d = w13;
 main_vbebd3d vbebd3d (
  .x_px(w0),
  .y_px(w1),
  .hsync(w2),
  .vsync(w3),
  .activeVideo(w4),
  .activeLineStart(w5),
  .activeLineEnd(w6),
  .activeFrameStart(w7),
  .activeFrameEnd(w8),
  .lineStart(w9),
  .lineEnd(w10),
  .frameStart(w11),
  .frameEnd(w12),
  .VGAStr(w13)
 );
endmodule

//---------------------------------------------------
//-- zipVGA
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Comprime las señales VGA en un único flujo.
//---------------------------------------------------

module main_vbebd3d (
 input [9:0] x_px,
 input [9:0] y_px,
 input hsync,
 input vsync,
 input activeVideo,
 input activeLineStart,
 input activeLineEnd,
 input activeFrameStart,
 input activeFrameEnd,
 input lineStart,
 input lineEnd,
 input frameStart,
 input frameEnd,
 output [29:0] VGAStr
);
 
 
 // alias 
 `define Active 0:0
 `define VS 1:1
 `define HS 2:2
 `define YC 12:3
 `define XC 22:13
 
 `define ALS 23:23
 `define ALE 24:24
 `define AFS 25:25
 `define AFE 26:26
 `define LS 27:27
 `define LE 28:28
 `define FS 29:29
 `define FE 30:30
 
 assign VGAStr[`XC] = x_px;
 assign VGAStr[`YC] = y_px;
 assign VGAStr[`HS] = hsync;
 assign VGAStr[`VS] = vsync;
 assign VGAStr[`Active] = activeVideo;
 	
 assign VGAStr[`ALS] = activeLineStart;
 assign VGAStr[`ALE] = activeLineEnd;
 assign VGAStr[`AFS] = activeFrameStart;
 assign VGAStr[`AFE] = activeFrameEnd;
 
 assign VGAStr[`LS] = lineStart;
 assign VGAStr[`LE] = lineEnd;
 assign VGAStr[`FS] = frameStart;
 assign VGAStr[`FE] = frameEnd;
endmodule
